#!/usr/bin/env node

require('rubico/global')
const cronist = require('cronist')
const fs = require('fs')
const FileSystem = require('./internal/FileSystem')
const walkPathForJSFilePaths = require('./internal/walkPathForJSFilePaths')
const { inspect } = require('util')

const readFileUtf8 = path => fs.promises.readFile(path, { encoding: 'utf8' })

const createMdastFile = async function (source, dest, options = {}) {
  await pipe(source, [
    readFileUtf8,
    cronist.parseMarkdown,
    data => fs.promises.writeFile(dest, `
export default ${inspect(data, {
  depth: Infinity,
  maxArrayLength: null,
  maxStringLength: Infinity,
})}
  `.trim()),
  ])
}

const createCronistFile = async function (source, dest, options = {}) {
  const { requiredKeys, ignoreDirs } = options
  await pipe(source, [
    curry.arity(2, walkPathForJSFilePaths, __, { ignoreDirs }),

    flatMap(async fileName => pipe(fileName, [
      readFileUtf8,
      cronist,

      filter(data => data.name && data.docs && Object.keys(data.mdast).length > 1),

      switchCase([
        data => data.length > 0 && data.some(item => item.name == 'GoogleChromeDevTools'),
        docsData => [{
          ...docsData.find(item => item.hasOwnProperty('constructor')),
          methods: [
            docsData.find(item => item.name == 'init'),
            docsData.find(item => item.name == 'setSessionId'),
            docsData.find(item => item.name == 'close'),
            ...docsData.filter(and([
              not(item => ['init', 'setSessionId', 'close'].includes(item.name)),
              not(item => item.name.includes('.')),
              not(item => item.hasOwnProperty('constructor')),
              not(item => item.name.startsWith('Event:')),
            ])),
            ...docsData.filter(and([
              item => item.name.includes('.'),
              not(item => item.hasOwnProperty('constructor')),
              not(item => item.name.startsWith('Event:')),
            ])),
            ...docsData.filter(and([
              not(item => item.hasOwnProperty('constructor')),
              item => item.name.startsWith('Event:'),
            ])),
          ],
        }],

        data => data.length > 0,
        ([classDocsData, ...methodsDocsData]) => [{
          ...classDocsData,
          methods: methodsDocsData,
        }],
        data => data,
      ]),

      map(assign({ fileName })),
    ])),

    data => fs.promises.writeFile(dest, `
export default ${inspect(data, {
  depth: Infinity,
  maxArrayLength: null,
  maxStringLength: Infinity,
})}
  `.trim()),
  ])
}

// createMdast() -> Promise<>
const createMdast = async function () {
  const presidiumVersion = require('../presidium/package').version
  const presidiumMajorVersion = presidiumVersion.split('.')[0]
  const presidiumWebSocketVersion = require('../presidium-websocket/package').version
  const presidiumWebSocketMajorVersion = presidiumWebSocketVersion.split('.')[0]
  const presidiumDBVersion = require('../presidium-db/package').version
  const presidiumDBMajorVersion = presidiumDBVersion.split('.')[0]

  console.log(`Creating mdast/presidium-v${presidiumMajorVersion}-readme.js`)
  await createMdastFile(
    `${__dirname}/../presidium/README.md`,
    `${__dirname}/public/mdast/presidium-v${presidiumMajorVersion}-readme.js`,
  )

  console.log(`Creating cronist/presidium-v${presidiumMajorVersion}.js`)
  await createCronistFile(
    `${__dirname}/../presidium`,
    `${__dirname}/public/cronist/presidium-v${presidiumMajorVersion}.js`,
    {
      requiredKeys: ['name', 'docs'],
      ignoreDirs: ['node_modules', 'archive'],
    },
  )

  console.log(`Creating cronist/presidium-websocket-v${presidiumWebSocketMajorVersion}.js`)
  await createCronistFile(
    `${__dirname}/../presidium-websocket`,
    `${__dirname}/public/cronist/presidium-websocket-v${presidiumWebSocketMajorVersion}.js`,
    {
      requiredKeys: ['name', 'docs'],
      ignoreDirs: ['node_modules', 'archive'],
    },
  )

  console.log(`Creating cronist/presidium-db-v${presidiumDBMajorVersion}.js`)
  await createCronistFile(
    `${__dirname}/../presidium-db`,
    `${__dirname}/public/cronist/presidium-db-v${presidiumDBMajorVersion}.js`,
    {
      requiredKeys: ['name', 'docs'],
      ignoreDirs: ['node_modules', 'archive'],
    },
  )

  console.log(`Creating presidium/v${presidiumMajorVersion}-filenames.js`)
  const presidiumFiles = require('../presidium/package').files
  await fs.promises.writeFile(`${__dirname}/public/presidium/v${presidiumMajorVersion}-filenames.js`, `
export default [
  ${presidiumFiles.map(name => `'${name}',`).join('\n  ')}
]
  `.trim())

  console.log(`Creating mdast/database-system-guide.js`)
  await createMdastFile(
    `${__dirname}/articles/database-system-guide.md`,
    `${__dirname}/public/mdast/database-system-guide.js`,
  )

}

if (require.main == module) {
  createMdast()
}

module.exports = createMdast
