#!/usr/bin/env node

const AwsCredentials = require('presidium/AwsCredentials')
const S3Bucket = require('presidium/S3Bucket')
const fs = require('fs')
const path = require('path')
const ContentType = require('./lib/ContentType')
const findPaths = require('./lib/findPaths')
const validateConfig = require('./lib/validateConfig')
const config = require('./config')

validateConfig(config)

const { domain, publicDir } = config

/**
 * @name main
 *
 * @synopsis
 * ```coffeescript [specscript]
 * main() -> Promise<>
 * ```
 */
async function main() {
  const awsCreds = await AwsCredentials('presidium')
  awsCreds.region = 'us-east-1'

  const bucket = new S3Bucket({
    name: domain,
    BlockPublicAccess: false,
    BlockPublicACLs: false,
    BlockPublicPolicy: false,
    IgnorePublicACLs: false,
    RestrictPublicBuckets: false,
    ...awsCreds,
  })
  await bucket.ready

  try {
    await bucket.getPolicy()
  } catch (_error) {
    const policy = {
      "Version": "2008-10-17",
      "Id": "Policy1380877762691",
      "Statement": [
        {
          "Sid": "Stmt1380877761162",
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "s3:GetObject",
          "Resource": `arn:aws:s3:::${domain}/*`,
        }
      ]
    }
    await bucket.putPolicy({ policy })
  }

  const dir = path.join(__dirname, publicDir)
  const paths = await findPaths(dir)

  for (const path of paths) {
    const key = path.replace(`${dir}/`, '')
    const contentBuffer = await fs.promises.readFile(path)
    const content = contentBuffer.toString('utf8')
    const contentType = ContentType(key, content)
    console.log(`Uploading ${path.replace(process.env.HOME, '~')} as ${key} [${contentType}]`)
    await bucket.putObject(key, content, {
      ContentType: contentType,
      Expires: new Date(),
    })
  }
}

main()
